In [1]:
import numpy as np

x1 = np.array([1,2,3])
x2 = np.array([4,5])
print(x1)
x3 = x1[:, np.newaxis]
print(x3)
x4 = np.transpose(x3)
print(x4)
x5 = np.transpose(x4)
print(x5)
x6 = x1.reshape((3,1))
print(x6)
# np.add(x1, x2)

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [2]:
x1 = np.array([[1,2,1],[0,4,-1]])
x2 = np.array([[1,2,1],[0,4,-1]])

x3 = x1.reshape((x1.shape[0], -1, x1.shape[1]))
x4 = x2.reshape((-1, x2.shape[0], x2.shape[1]))

# print(x3.shape) # (2,1,3)
print("x3: ",)
print(x3)
# print(x4.shape) # (1,2,3)
print("x4: ",)
print(x4)

x3: 
[[[ 1  2  1]]

 [[ 0  4 -1]]]
x4: 
[[[ 1  2  1]
  [ 0  4 -1]]]


If 

In [6]:
x5 = x3 - x4
print(x5.shape)
# x6 = np.sum(x5**2, axis = 0) # This produces wrong value with the shape (2,3)
# print(x6)
# print(x6.shape)
# x7 = np.sum(x5**2, axis = 1) # This produces wrong value (same as above) with the shape (2,3)
# print(x7)
# print(x7.shape)
# np.sum(x5**2, axis = -1) # This reduces the shape to (2,2) 
# np.sum(x5**2, axis = 2) # This reduces the shape to (2,2) 

(2, 2, 3)


array([[0, 9],
       [9, 0]])

Implementing sigmoid function for SVM kernel

In [4]:
sigma = 2
sim = np.exp(- np.sum(x5**2, axis = -1)/(2*sigma*2))
print(sim)

[[1.         0.32465247]
 [0.32465247 1.        ]]


In [11]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])