In [15]:
import numpy as np

x1 = np.array([1,2,3])
x2 = np.array([4,5])
print(x1)
x3 = x1[:, np.newaxis]
print(x3)
x4 = np.transpose(x3)
print(x4)
x5 = np.transpose(x4)
print(x5)
x6 = x1.reshape((3,1))
print(x6)
# np.add(x1, x2)

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [41]:
x1 = np.array([[1,2,1],[0,4,-1]])
x2 = np.array([[1,2,1],[0,4,-1]])

x3 = x1.reshape((x1.shape[0], -1, x1.shape[1]))
x4 = x2.reshape((-1, x2.shape[0], x2.shape[1]))

# print(x3.shape) # (2,1,3)
print("x3: ",)
print(x3)
# print(x4.shape) # (1,2,3)
print("x4: ",)
print(x4)

x3: 
[[[ 1  2  1]]

 [[ 0  4 -1]]]
x4: 
[[[ 1  2  1]
  [ 0  4 -1]]]


In [49]:
x5 = x3 - x4
# x6 = np.sum(x5**2, axis = 0) # This produces wrong value with the shape (2,3)
# print(x6)
# print(x6.shape)
# x7 = np.sum(x5**2, axis = 1) # This produces wrong value (same as above) with the shape (2,3)
# print(x7)
# print(x7.shape)
# np.sum(x5**2, axis = -1) # This reduces the shape to (2,2) 

Implementing sigmoid function for SVM kernel

In [51]:
sigma = 2
sim = np.exp(- np.sum(x5**2, axis = -1)/(2*sigma*2))
print(sim)

[[1.         0.32465247]
 [0.32465247 1.        ]]
